Payment fixes and storybook tweeks:
frontastic-developers/customer-thegoodstore pull request #292
Opened 2023-04-03 09:42 UTC by KenwayTheGreat

- Added content tweek for the search component
- Added card number format and error messages

2023-04-03 22:35 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.04.03.22.34-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.04.03.22.34-test&branch=payment-fixes-and-storybook-tweeks) on branch [`payment-fixes-and-storybook-tweeks`](https://github.com/frontastic-developers/customer-thegoodstore/tree/payment-fixes-and-storybook-tweeks) successful

Commit [`89031d2b`](https://github.com/frontastic-developers/customer-thegoodstore/commit/89031d2bc73eeb2bcfe13b677dd3a6ec44d547c4) by *KenwayTheGreat* in 0:33

2023-04-03 22:40 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.04.03.22.39-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.04.03.22.39-test&branch=payment-fixes-and-storybook-tweeks) on branch [`payment-fixes-and-storybook-tweeks`](https://github.com/frontastic-developers/customer-thegoodstore/tree/payment-fixes-and-storybook-tweeks) successful

Commit [`8189b1cf`](https://github.com/frontastic-developers/customer-thegoodstore/commit/8189b1cf01d235bdda3595157dac9ea98ad484b0) by *KenwayTheGreat* in 0:29

2023-04-04 08:15 UTC, minabadrous requested changes

2023-04-04 08:15 UTC, minabadrous commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/useAddPaymentMethod.ts
> +      if (e.target.value.length > 0 && !/^ *[0-9][0-9 ]*$/.test(e.target.value)) {
Just a suggestion:
I think it would be more readable to store the Regex first in a variable that is descriptive of what it's looking for. And then run the string against that one.

2023-04-04 08:15 UTC, minabadrous commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/useEditPaymentMethod.ts
> +      payments[payments.findIndex((payment) => payment.id === paymentId)] = {
Again here a suggestion for better readability to store first the result of what index you are trying to find and then use it with a descriptive variable.

2023-04-04 08:15 UTC, minabadrous commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/useFormatCredit.ts
> +const useFormatCreditCard = (cardNumber: string) => {
For me I find this function very not descriptive also because I have to try to understand what every Regex does and what every step in the function is trying to do.

2023-04-04 08:15 UTC, minabadrous commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/usePaymentHelpers.ts
> +      if (month == 12) (month = 1), (year += 1);
here too i my opinion.

2023-04-04 08:15 UTC, minabadrous commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/payment-add/index.tsx
> +        <div className="mt-24 md:w-[372px] lg:mt-0">
Both numbers added here, are we sure they should be in this same way or do we actually need it to be more responsive?
Also: all our spacings should be divisible by four which is not the case for the `799` width. I assume you can go with  800. Although I still think there would be a way to do this more dynamically without fixed values.

2023-04-04 08:22 UTC, KenwayTheGreat commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/payment-add/index.tsx
> +        <div className="mt-24 md:w-[372px] lg:mt-0">
I copied the width values from figma; I can adjust them for readability

2023-04-04 08:23 UTC, KenwayTheGreat commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/usePaymentHelpers.ts
> +      if (month == 12) (month = 1), (year += 1);
I'm not sure what can be done for this block in terms of readability

2023-04-04 08:34 UTC, KenwayTheGreat commented on packages/home/frontend/components/commercetools-ui/organisms/account/sections/payment-methods/helper-hooks/useAddPaymentMethod.ts
> +      if (e.target.value.length > 0 && !/^ *[0-9][0-9 ]*$/.test(e.target.value)) {
Yes I agree

2023-04-04 11:14 UTC, minabadrous approved these changes

2023-04-04 11:15 UTC, merged