Fixed move to cart on out of stock items
frontastic-developers/customer-thegoodstore pull request #305
Opened 2023-04-30 12:01 UTC by KenwayTheGreat

2023-04-30 12:04 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.04.30.12.04-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.04.30.12.04-test&branch=wishlist-small-fix) on branch [`wishlist-small-fix`](https://github.com/frontastic-developers/customer-thegoodstore/tree/wishlist-small-fix) successful

Commit [`9c5fd4c4`](https://github.com/frontastic-developers/customer-thegoodstore/commit/9c5fd4c43695453a3e376445a9eaaa8680503510) by *KenwayTheGreat* in 0:39

2023-05-02 07:43 UTC, minabadrous approved these changes

2023-05-02 08:09 UTC, abdotaker608 requested changes

2023-05-02 08:09 UTC, abdotaker608 commented on packages/home/frontend/components/commercetools-ui/organisms/wishlist/components/wishlist-item.tsx
> +          <Button variant="primary" onClick={moveToCart} disabled={!item.variant?.isOnStock? true : false} className="py-8 text-14">
I guess you can just do `disabled={!item.variant?.isOnStock}`

2023-05-02 08:50 UTC, merged