Fix (FP-4348): Fixed the left menu for account
frontastic-developers/customer-thegoodstore pull request #332
Opened 2023-06-01 11:49 UTC by KenwayTheGreat

2023-06-01 11:53 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.06.01.11.51-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.01.11.51-test&branch=fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) on branch [`fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) successful

Commit [`e1836264`](https://github.com/frontastic-developers/customer-thegoodstore/commit/e18362642d23e7581d5e9756f2e9a1098c93ae0e) by *KenwayTheGreat* in 1:53

2023-06-05 09:35 UTC, abdotaker608 requested changes

2023-06-05 09:35 UTC, abdotaker608 commented on packages/home/frontend/components/commercetools-ui/organisms/account/index.tsx
> +      accountPagesRef[id as 'edit-personal-info' | 'edit-newsletter' | 'change-password' | 'delete-account'] ?? (
Let's not do this hard coding, whenever we add an entry to this `accountPagesRef` you need to update this as well. You can use `as keyof typeof accountPagesRef` instead

2023-06-05 09:35 UTC, abdotaker608 commented on packages/home/frontend/components/commercetools-ui/organisms/account/index.tsx
> +    return addressPagesRef[id?.split('-')[0] as 'add' | 'edit'] ?? <Addresses />;
Same as above `as keyof typeof addressPagesRef`

2023-06-05 11:01 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.06.05.10.59-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.05.10.59-test&branch=fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) on branch [`fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) successful

Commit [`cb07b5b8`](https://github.com/frontastic-developers/customer-thegoodstore/commit/cb07b5b8025cc6cca7dd6506555eb1bebfb6f66f) by *KenwayTheGreat* in 1:52

2023-06-05 12:51 UTC, frontastic-developers commented
## :white_check_mark: Tests [2023.06.05.12.49-test](https://thegoodstore.frontastic.io/developer/continuousIntegration?build=2023.06.05.12.49-test&branch=fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) on branch [`fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages`](https://github.com/frontastic-developers/customer-thegoodstore/tree/fix/FP-4348-category-in-left-navigation-dropdown-should-stay-active-when-opening-sub-pages) successful

Commit [`e874fd1b`](https://github.com/frontastic-developers/customer-thegoodstore/commit/e874fd1b09b64c618fa2acef7252bd18a19abd21) by *KenwayTheGreat* in 2:05

2023-06-11 12:00 UTC, abdotaker608 approved these changes

2023-06-12 09:55 UTC, xcintas approved these changes

2023-06-12 09:57 UTC, merged